language: node_js
node_js: '10'
sudo: required
script: "./cli/deploy.sh"
env:
  global:
    secure: EjLLVLuURbA+n6sxHt/mzQIU5O2mgbiGYRED+q+/3SRgexp+cdcPrMpyDd1i7jrb1smSJ50+qhlwENSEsLHaMpPZ1SfrNBJFWZyHE0qi3EubUFNi/rziu0AS9dtykKn5hkxLJCNEk7+Hx0ITfSyET0qwvJDhgNO3Bq++Xsex+pirmGeC6F24sdnGLU6WqiLxaRz7TJzH8uX8t4G9+Zrs52Fws4BqpedylUlsUZjoNz5tmgZJj59optPOVZyNOMl9wUONEyszBRNRpVsSt6iBbw/md+IRDfz/2g87FQdTmfraTTC+ovyqoNKbhPPahFSbDJLZlCDVXgS3JaJ/WFQJZxbOjwoevN+Sz2flXqtmM9rlU+gE3dxcTEPZkFdfze92oaFGLi62ev/DYL19S/zVxUnbXRNBaPvDB67eIyqTGsFuQnW6y/mGFqwt26iL6e8ohiWXdlDjgpr7fMLhhTlxwr+bGM2NYxAQ2/AjL9mkzsciAvhTNYvu5dpzzLi5sU+J8dA4NMr44R/KKI2lmXWD7sOxy2GAEXl6TIpDcB3KNeiZjTKe1h5eCv45yD6kJTcvQpxnmNvBe9rLaQmmLkGG5tjRyhqF4jsbBbuQG7xey47iX+f63NOwUfo3nJZO3rhWgfLlBYpZUee3gQbKi9oqQd544BUWFtc+0KLeb41/mEQ=
