language: node_js
node_js: '10'
sudo: required
script: "./cli/deploy.sh"
env:
  global:
    secure: DTlkLu1mWzOcvYplJX1ioimuDZLDhlcMjQ/5Id1gWHrrubONamrYsYC5Bvc3yWBc/68w49BArjNGMI3EaCeecYLGX1wwEVY9XFipZZniWwGDpKEnojjpHLf6XZW/EFGWX5nuj7WNewYiKqJJBzcC2DqHKE96OunVkZHu/dDll8GB7mF5zHEhVUTMVADBgCBQX7gbRJLTf9i0mrCvrR2boSe/34zZeo1CuoP5mQTed6lPQtpJUPHC6ovnpNO0GpeX7WKb3BWH/mFaQD/xC74zItjsjvcTPZUaaLuRePyrLS4mfqTbkfUhyLh4SN1+6OOWb7AIBtnpbAylPI0ZBhaYuRwQ/tiGEibHJfGC6oBJiw85TQImvjImMBGcHS/0b/DfUbyP6idX4yKhLiLZHWSb/lUCOIo0GNkNYZKf/N9krRkhSPPW2rPYIv4RzH/9kdLQXnAWGWgIbj7/0C4brBtUC9OE1uYCVSj9oGA6gS4/iFW1aIaAav8+1ViXEmRigJkqdtYhgUoMPW7JVKGMS5DfWfPJ645NBIH2frY5Q4jR4ADyN5b8sWFgfrsSK/xUwoz6dV/jIMLkla6yInZk1n6lmoWuyWFSx+mV/XURw3oY1ZbYV7UhpOgqWfwuSTk/orgchaBMxUv/CeMAB4TOVOjjZs2cW/02QkcEn7kVCujkEDA=
